### ISSUE TITLE
add a optional configuration to set optimization level

### ISSUE THREAD

**Issue by 9sako6** [9sako6/imgcmp#20]
e.g.:

```yml
name: imgcmp
on: pull_request
jobs:
  build:
    name: imgcmp
    runs-on: ubuntu-latest    
    steps:
    - uses: 9sako6/imgcmp@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IGNORED_FILES: "public/*:posts/*.svg"
        JPEG_QUALITY: 60
```
